name: CI
on: 
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Uses Node JS
      - uses: |
          actions/checkout@v2
          action/setup-node@v2
        with:
          node-version: '14'
      - run: |
          npm install
          npm test -- --coverage
        env:
          CI: true