name: CI
on: 
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{hashFiles('**/packadge-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
            

      - name: Uses Node JS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
      - name: Deploy to staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain  relieved-sun.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN}}

          
      