name: CI
on: 
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2.4.0
      - name: Uses Node JS
        uses: action/setup-node@v2
        with:
          node-version: '14'
        run: |
          npm install
          npm test -- --coverage
        env:
          CI: true